---
ops_cloudwatch_enabled: false
ops_cloudwatch_region: eu-north-1
ops_cloudwatch_metrics_interval_seconds: 300
ops_cloudwatch_access_log_group: ""
ops_cloudwatch_error_log_group: ""
ops_cloudwatch_package_url: https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
ops_cloudwatch_signature_url: https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb.sig
ops_cloudwatch_signing_key_url: https://amazoncloudwatch-agent.s3.amazonaws.com/assets/amazon-cloudwatch-agent.gpg
ops_cloudwatch_signing_fingerprint: 937616F3450B7D806CBD9725D58167303B789C72
